In [176]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Import your dataset which contain at least 2 tables. And then create NaN value in your dataset for practice.

In [119]:
df = pd.read_csv('/content/application_record.csv',delimiter=',', on_bad_lines='skip')
df2 = pd.read_csv('/content/credit_record.csv',delimiter=',', on_bad_lines='skip')

<ipython-input-119-9e8c734c1775>:1: DtypeWarning: Columns (0,4,5,10,11,12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/application_record.csv',delimiter=',', on_bad_lines='skip')
<ipython-input-119-9e8c734c1775>:2: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('/content/credit_record.csv',delimiter=',', on_bad_lines='skip')

In [19]:
df.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0.0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0.0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0.0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1.0,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1.0,Sales staff,1.0

In [21]:
df2.head()

        ID MONTHS_BALANCE STATUS
0  5001711            0.0      X
1  5001711           -1.0      0
2  5001711           -2.0      0
3  5001711           -3.0      0
4  5001712            0.0      C

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851735 entries, 0 to 851734
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   851735 non-null  object
 1   CODE_GENDER          851735 non-null  object
 2   FLAG_OWN_CAR         851735 non-null  object
 3   FLAG_OWN_REALTY      851735 non-null  object
 4   CNT_CHILDREN         851735 non-null  object
 5   AMT_INCOME_TOTAL     851735 non-null  object
 6   NAME_INCOME_TYPE     851735 non-null  object
 7   NAME_EDUCATION_TYPE  851734 non-null  object
 8   NAME_FAMILY_STATUS   851733 non-null  object
 9   NAME_HOUSING_TYPE    851726 non-null  object
 10  DAYS_BIRTH           851725 non-null  object
 11  DAYS_EMPLOYED        851720 non-null  object
 12  FLAG_MOBIL           851716 non-null  object
 13  FLAG_WORK_PHONE      851711 non-null  object
 14  FLAG_PHONE           851711 non-null  object
 15  FLAG_EMAIL           851707 non-null  object
 16  OCCUPATION_TYPE      591238 non-null  object
 17  CNT_FAM_MEMBERS      851697 non-null  float64
dtypes: float64(1), object(17)
memory usage: 117.0+ MB

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1882350 entries, 0 to 1882349
Data columns (total 3 columns):
 #   Column          Dtype
---  ------          -----
 0   ID              object
 1   MONTHS_BALANCE  object
 2   STATUS          object
dtypes: object(3)
memory usage: 43.1+ MB

In [23]:
df.tail()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
851730,6840104,M,N,Y,0,135000.0,Pensioner,Secondary / secondary special,Separated,House / apartment,-22717.0,365243.0,1.0,0.0,0.0,0.0,NaN,1.0
851731,6840222,F,N,N,0,103500.0,Working,Secondary / secondary special,Single / not married,House / apartment,-15939.0,-3007.0,1.0,0.0,0.0,0.0,Laborers,1.0
851732,6841878,F,N,N,0,54000.0,Commercial associate,Higher education,Single / not married,With parents,-8169.0,-372.0,1.0,1.0,0.0,0.0,Sales staff,1.0
851733,6842765,F,N,Y,0,72000.0,Pensioner,Secondary / secondary special,Married,House / apartment,-21673.0,365243.0,1.0,0.0,0.0,0.0,NaN,2.0
851734,6842885,F,N,Y,0,121500.0,Working,Secondary / secondary special,Married,House / apartment,-18858.0,-1201.0,1.0,0.0,1.0,0.0,Sales staff,2.0

In [24]:
df2.tail()

              ID MONTHS_BALANCE STATUS
1882345  5150487            -25      C
1882346  5150487            -26      C
1882347  5150487            -27      C
1882348  5150487            -28      C
1882349  5150487            -29      C

In [25]:
df.describe()

       CNT_FAM_MEMBERS
count    851697.000000
mean          2.194883
std           0.897211
min           1.000000
25%           2.000000
50%           2.000000
75%           3.000000
max          20.000000

In [26]:
df2.describe()

             ID  MONTHS_BALANCE   STATUS
count   1882350       1882348.0  1882340
unique    51688           128.0        8
top     5096879            -1.0        C
freq        122         35762.0   794296

In [27]:
df.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         1
NAME_FAMILY_STATUS          2
NAME_HOUSING_TYPE           9
DAYS_BIRTH                 10
DAYS_EMPLOYED              15
FLAG_MOBIL                 19
FLAG_WORK_PHONE            24
FLAG_PHONE                 24
FLAG_EMAIL                 28
OCCUPATION_TYPE        260497
CNT_FAM_MEMBERS            38
dtype: int64

In [29]:
df2.isnull().sum()

ID                 0
MONTHS_BALANCE     2
STATUS            10
dtype: int64

In [120]:
pd.set_option("display.max_rows",11)
pd.set_option("display.expand_frame_repr",False)

df

             ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY CNT_CHILDREN AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  NAME_HOUSING_TYPE DAYS_BIRTH DAYS_EMPLOYED FLAG_MOBIL FLAG_WORK_PHONE FLAG_PHONE FLAG_EMAIL OCCUPATION_TYPE  CNT_FAM_MEMBERS
0       5008804           M            Y               Y            0         427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542          1               1          0        0.0             NaN              2.0
1       5008805           M            Y               Y            0         427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542          1               1          0        0.0             NaN              2.0
2       5008806           M            Y               Y            0         112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474         -1134          1               0          0        0.0  Security staff              2.0
3       5008808           F            N               Y            0         270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051          1               0          1        1.0     Sales staff              1.0
4       5008809           F            N               Y            0         270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051          1               0          1        1.0     Sales staff              1.0
...         ...         ...          ...             ...          ...              ...                   ...                            ...                   ...                ...        ...           ...        ...             ...        ...        ...             ...              ...
851730  6840104           M            N               Y            0         135000.0             Pensioner  Secondary / secondary special             Separated  House / apartment   -22717.0      365243.0        1.0             0.0        0.0        0.0             NaN              1.0
851731  6840222           F            N               N            0         103500.0               Working  Secondary / secondary special  Single / not married  House / apartment   -15939.0       -3007.0        1.0             0.0        0.0        0.0        Laborers              1.0
851732  6841878           F            N               N            0          54000.0  Commercial associate               Higher education  Single / not married       With parents    -8169.0        -372.0        1.0             1.0        0.0        0.0     Sales staff              1.0
851733  6842765           F            N               Y            0          72000.0             Pensioner  Secondary / secondary special               Married  House / apartment   -21673.0      365243.0        1.0             0.0        0.0        0.0             NaN              2.0
851734  6842885           F            N               Y            0         121500.0               Working  Secondary / secondary special               Married  House / apartment   -18858.0       -1201.0        1.0             0.0        1.0        0.0     Sales staff              2.0

[851735 rows x 18 columns]

In [40]:
df2

              ID MONTHS_BALANCE STATUS
0        5001711            0.0      X
1        5001711           -1.0      0
2        5001711           -2.0      0
3        5001711           -3.0      0
4        5001712            0.0      C
...          ...            ...    ...
1882345  5150487            -25      C
1882346  5150487            -26      C
1882347  5150487            -27      C
1882348  5150487            -28      C
1882349  5150487            -29      C

[1882350 rows x 3 columns]

In [129]:
df.columns = ['ID', 'Gender', 'Own_Car', 'Own_Realty', 'Children', 'Annual_Income', 'Income_Type', 'Education_Level', 'Marital_Status', 'Housing', 'Days_Birth', "Days_Employed", 'Mobile_Phone', 'Work_Phone', 'Phone', 'Email', 'Ocupation', 'Family_Size']

In [121]:
df.set_index('ID', inplace=True)
df

        CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY CNT_CHILDREN AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  NAME_HOUSING_TYPE DAYS_BIRTH DAYS_EMPLOYED FLAG_MOBIL FLAG_WORK_PHONE FLAG_PHONE FLAG_EMAIL OCCUPATION_TYPE  CNT_FAM_MEMBERS
ID
5008804           M            Y               Y            0         427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542          1               1          0        0.0             NaN              2.0
5008805           M            Y               Y            0         427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542          1               1          0        0.0             NaN              2.0
5008806           M            Y               Y            0         112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474         -1134          1               0          0        0.0  Security staff              2.0
5008808           F            N               Y            0         270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051          1               0          1        1.0     Sales staff              1.0
5008809           F            N               Y            0         270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051          1               0          1        1.0     Sales staff              1.0
...             ...          ...             ...          ...              ...                   ...                            ...                   ...                ...        ...           ...        ...             ...        ...        ...             ...              ...
6840104           M            N               Y            0         135000.0             Pensioner  Secondary / secondary special             Separated  House / apartment   -22717.0      365243.0        1.0             0.0        0.0        0.0             NaN              1.0
6840222           F            N               N            0         103500.0               Working  Secondary / secondary special  Single / not married  House / apartment   -15939.0       -3007.0        1.0             0.0        0.0        0.0        Laborers              1.0
6841878           F            N               N            0          54000.0  Commercial associate               Higher education  Single / not married       With parents    -8169.0        -372.0        1.0             1.0        0.0        0.0     Sales staff              1.0
6842765           F            N               Y            0          72000.0             Pensioner  Secondary / secondary special               Married  House / apartment   -21673.0      365243.0        1.0             0.0        0.0        0.0             NaN              2.0
6842885           F            N               Y            0         121500.0               Working  Secondary / secondary special               Married  House / apartment   -18858.0       -1201.0        1.0             0.0        1.0        0.0     Sales staff              2.0

[851735 rows x 17 columns]

In [122]:
df.reset_index(inplace=True)
df

             ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY CNT_CHILDREN AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  NAME_HOUSING_TYPE DAYS_BIRTH DAYS_EMPLOYED FLAG_MOBIL FLAG_WORK_PHONE FLAG_PHONE FLAG_EMAIL OCCUPATION_TYPE  CNT_FAM_MEMBERS
0       5008804           M            Y               Y            0         427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542          1               1          0        0.0             NaN              2.0
1       5008805           M            Y               Y            0         427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542          1               1          0        0.0             NaN              2.0
2       5008806           M            Y               Y            0         112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474         -1134          1               0          0        0.0  Security staff              2.0
3       5008808           F            N               Y            0         270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051          1               0          1        1.0     Sales staff              1.0
4       5008809           F            N               Y            0         270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051          1               0          1        1.0     Sales staff              1.0
...         ...         ...          ...             ...          ...              ...                   ...                            ...                   ...                ...        ...           ...        ...             ...        ...        ...             ...              ...
851730  6840104           M            N               Y            0         135000.0             Pensioner  Secondary / secondary special             Separated  House / apartment   -22717.0      365243.0        1.0             0.0        0.0        0.0             NaN              1.0
851731  6840222           F            N               N            0         103500.0               Working  Secondary / secondary special  Single / not married  House / apartment   -15939.0       -3007.0        1.0             0.0        0.0        0.0        Laborers              1.0
851732  6841878           F            N               N            0          54000.0  Commercial associate               Higher education  Single / not married       With parents    -8169.0        -372.0        1.0             1.0        0.0        0.0     Sales staff              1.0
851733  6842765           F            N               Y            0          72000.0             Pensioner  Secondary / secondary special               Married  House / apartment   -21673.0      365243.0        1.0             0.0        0.0        0.0             NaN              2.0
851734  6842885           F            N               Y            0         121500.0               Working  Secondary / secondary special               Married  House / apartment   -18858.0       -1201.0        1.0             0.0        1.0        0.0     Sales staff              2.0

[851735 rows x 18 columns]

In [123]:
df.index.name = 'Order'
df2.index.name = 'Order'

In [124]:
df.head()

            ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY CNT_CHILDREN AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  NAME_HOUSING_TYPE DAYS_BIRTH DAYS_EMPLOYED FLAG_MOBIL FLAG_WORK_PHONE FLAG_PHONE FLAG_EMAIL OCCUPATION_TYPE  CNT_FAM_MEMBERS
Order
0      5008804           M            Y               Y            0         427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542          1               1          0        0.0             NaN              2.0
1      5008805           M            Y               Y            0         427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542          1               1          0        0.0             NaN              2.0
2      5008806           M            Y               Y            0         112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474         -1134          1               0          0        0.0  Security staff              2.0
3      5008808           F            N               Y            0         270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051          1               0          1        1.0     Sales staff              1.0
4      5008809           F            N               Y            0         270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051          1               0          1        1.0     Sales staff              1.0

In [125]:
df.index+=1
df2.index+=1

In [126]:
df2.head()

            ID MONTHS_BALANCE STATUS
Order
1      5001711            0.0      X
2      5001711           -1.0      0
3      5001711           -2.0      0
4      5001711           -3.0      0
5      5001712            0.0      C

In [130]:
df_melted = pd.melt(df, id_vars=['ID'], value_vars=['Mobile_Phone', 'Work_Phone', 'Phone', 'Email'], var_name='Communication', value_name='Y_N')

In [131]:
df_melted

              ID Communication  Y_N
0        5008804  Mobile_Phone    1
1        5008805  Mobile_Phone    1
2        5008806  Mobile_Phone    1
3        5008808  Mobile_Phone    1
4        5008809  Mobile_Phone    1
...          ...           ...  ...
3406935  6840104         Email  0.0
3406936  6840222         Email  0.0
3406937  6841878         Email  0.0
3406938  6842765         Email  0.0
3406939  6842885         Email  0.0

[3406940 rows x 3 columns]

In [132]:
duplicates=df_melted.duplicated()
df_melted[duplicates]

              ID Communication  Y_N
65536    6723301  Mobile_Phone  1.0
65537    6723302  Mobile_Phone  1.0
65538    5114550  Mobile_Phone  1.0
65539    5114551  Mobile_Phone  1.0
65540    5114552  Mobile_Phone  1.0
...          ...           ...  ...
3406935  6840104         Email  0.0
3406936  6840222         Email  0.0
3406937  6841878         Email  0.0
3406938  6842765         Email  0.0
3406939  6842885         Email  0.0

[1070747 rows x 3 columns]

In [89]:
#df_unique=df_melted.drop_duplicates()

In [133]:
df_melted['Y_N']=pd.to_numeric(df_melted['Y_N'], errors='coerce')
df_melted

              ID Communication  Y_N
0        5008804  Mobile_Phone  1.0
1        5008805  Mobile_Phone  1.0
2        5008806  Mobile_Phone  1.0
3        5008808  Mobile_Phone  1.0
4        5008809  Mobile_Phone  1.0
...          ...           ...  ...
3406935  6840104         Email  0.0
3406936  6840222         Email  0.0
3406937  6841878         Email  0.0
3406938  6842765         Email  0.0
3406939  6842885         Email  0.0

[3406940 rows x 3 columns]

In [134]:
df_pivot = df_melted.pivot_table(index='ID', columns='Communication', values='Y_N', aggfunc='mean')

In [135]:
df_pivot

Communication  Email  Mobile_Phone  Phone  Work_Phone
ID
55000.0          NaN           1.0    NaN         NaN
5008804          0.0           1.0    0.0         1.0
5008805          0.0           1.0    0.0         1.0
5008806          0.0           1.0    0.0         0.0
5008808          1.0           1.0    1.0         0.0
...              ...           ...    ...         ...
7999660          0.0           1.0    0.0         0.0
7999696          0.0           1.0    0.0         0.0
7999738          0.0           1.0    0.0         0.0
7999784          0.0           1.0    0.0         0.0
7999952          0.0           1.0    0.0         0.0

[513143 rows x 4 columns]

In [136]:
merged_df = df.merge(df2, on='ID', how='inner')

In [137]:
merged_df

              ID Gender Own_Car Own_Realty Children Annual_Income Income_Type                Education_Level Marital_Status            Housing Days_Birth Days_Employed Mobile_Phone Work_Phone Phone Email    Ocupation  Family_Size MONTHS_BALANCE STATUS
0        5112956      M       Y          Y        0      270000.0     Working               Higher education        Married  House / apartment     -16872          -769            1          1     1   1.0  Accountants          2.0            0.0      X
1        5112956      M       Y          Y        0      270000.0     Working               Higher education        Married  House / apartment     -16872          -769            1          1     1   1.0  Accountants          2.0           -1.0      X
2        5112956      M       Y          Y        0      270000.0     Working               Higher education        Married  House / apartment     -16872          -769            1          1     1   1.0  Accountants          2.0           -2.0      X
3        5112956      M       Y          Y        0      270000.0     Working               Higher education        Married  House / apartment     -16872          -769            1          1     1   1.0  Accountants          2.0           -3.0      0
4        5112956      M       Y          Y        0      270000.0     Working               Higher education        Married  House / apartment     -16872          -769            1          1     1   1.0  Accountants          2.0           -4.0      0
...          ...    ...     ...        ...      ...           ...         ...                            ...            ...                ...        ...           ...          ...        ...   ...   ...          ...          ...            ...    ...
1063785  5034015      F       N          Y        1      135000.0     Working  Secondary / secondary special        Married  House / apartment   -16609.0        -186.0          1.0        0.0   0.0   0.0     Laborers          3.0          -35.0      0
1063786  5034015      F       N          Y        1      135000.0     Working  Secondary / secondary special        Married  House / apartment   -16609.0        -186.0          1.0        0.0   0.0   0.0     Laborers          3.0          -36.0      0
1063787  5034015      F       N          Y        1      135000.0     Working  Secondary / secondary special        Married  House / apartment   -16609.0        -186.0          1.0        0.0   0.0   0.0     Laborers          3.0          -37.0      0
1063788  5034015      F       N          Y        1      135000.0     Working  Secondary / secondary special        Married  House / apartment   -16609.0        -186.0          1.0        0.0   0.0   0.0     Laborers          3.0          -38.0      0
1063789  5034015      F       N          Y        1      135000.0     Working  Secondary / secondary special        Married  House / apartment   -16609.0        -186.0          1.0        0.0   0.0   0.0     Laborers          3.0          -39.0      X

[1063790 rows x 20 columns]

In [138]:
merged_df2 = df.merge(df2, on='ID', how='outer')

In [139]:
merged_df2

                                   ID             Gender            Own_Car Own_Realty           Children Annual_Income    Income_Type                Education_Level  Marital_Status            Housing Days_Birth Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation  Family_Size MONTHS_BALANCE STATUS
0                                   5                NaN                NaN        NaN                NaN           NaN            NaN                            NaN             NaN                NaN        NaN           NaN          NaN        NaN   NaN   NaN             NaN          NaN              0    NaN
1                             55000.0            Working  Incomplete higher      Widow  House / apartment      -19927.0          -3615                              1               0                  0        1.0      Laborers          1.0        NaN   NaN   NaN             NaN          NaN            NaN    NaN
2                             5008804                  M                  Y          Y                  0      427500.0        Working               Higher education  Civil marriage   Rented apartment     -12005         -4542            1          1     0   0.0             NaN          2.0            NaN    NaN
3                             5008805                  M                  Y          Y                  0      427500.0        Working               Higher education  Civil marriage   Rented apartment     -12005         -4542            1          1     0   0.0             NaN          2.0            NaN    NaN
4                             5008806                  M                  Y          Y                  0      112500.0        Working  Secondary / secondary special         Married  House / apartment     -21474         -1134            1          0     0   0.0  Security staff          2.0            NaN    NaN
...                               ...                ...                ...        ...                ...           ...            ...                            ...             ...                ...        ...           ...          ...        ...   ...   ...             ...          ...            ...    ...
2751975                       7999952                  F                  N          Y                  1      157500.0  State servant               Higher education         Married  House / apartment   -15859.0       -3679.0          1.0        0.0   0.0   0.0      Core staff          3.0            NaN    NaN
2751976  7condary / secondary special            Married  House / apartment     -10047               -267           1.0              1                              0               0        Sales staff        3.0           NaN          NaN        NaN   NaN   NaN             NaN          NaN            NaN    NaN
2751977                             C                NaN                NaN        NaN                NaN           NaN            NaN                            NaN             NaN                NaN        NaN           NaN          NaN        NaN   NaN   NaN             NaN          NaN            NaN    NaN
2751978                             d  House / apartment             -16675      -5056                  1           1.0              1                              0         Drivers                2.0        NaN           NaN          NaN        NaN   NaN   NaN             NaN          NaN            NaN    NaN
2751979                     y special            Married  House / apartment     -18286              -2789           1.0              0                              0               0     Security staff        2.0           NaN          NaN        NaN   NaN   NaN             NaN          NaN            NaN    NaN

[2751980 rows x 20 columns]

In [140]:
concatenated_pd = pd.concat([df,df2], axis=1)

In [141]:
concatenated_pd

              ID Gender Own_Car Own_Realty Children Annual_Income           Income_Type                Education_Level        Marital_Status            Housing  ... Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation Family_Size       ID MONTHS_BALANCE STATUS
Order                                                                                                                                                            ...
1        5008804      M       Y          Y        0      427500.0               Working               Higher education        Civil marriage   Rented apartment  ...         -4542            1          1     0   0.0             NaN         2.0  5001711            0.0      X
2        5008805      M       Y          Y        0      427500.0               Working               Higher education        Civil marriage   Rented apartment  ...         -4542            1          1     0   0.0             NaN         2.0  5001711           -1.0      0
3        5008806      M       Y          Y        0      112500.0               Working  Secondary / secondary special               Married  House / apartment  ...         -1134            1          0     0   0.0  Security staff         2.0  5001711           -2.0      0
4        5008808      F       N          Y        0      270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment  ...         -3051            1          0     1   1.0     Sales staff         1.0  5001711           -3.0      0
5        5008809      F       N          Y        0      270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment  ...         -3051            1          0     1   1.0     Sales staff         1.0  5001712            0.0      C
...          ...    ...     ...        ...      ...           ...                   ...                            ...                   ...                ...  ...           ...          ...        ...   ...   ...             ...         ...      ...            ...    ...
1882346      NaN    NaN     NaN        NaN      NaN           NaN                   NaN                            NaN                   NaN                NaN  ...           NaN          NaN        NaN   NaN   NaN             NaN         NaN  5150487            -25      C
1882347      NaN    NaN     NaN        NaN      NaN           NaN                   NaN                            NaN                   NaN                NaN  ...           NaN          NaN        NaN   NaN   NaN             NaN         NaN  5150487            -26      C
1882348      NaN    NaN     NaN        NaN      NaN           NaN                   NaN                            NaN                   NaN                NaN  ...           NaN          NaN        NaN   NaN   NaN             NaN         NaN  5150487            -27      C
1882349      NaN    NaN     NaN        NaN      NaN           NaN                   NaN                            NaN                   NaN                NaN  ...           NaN          NaN        NaN   NaN   NaN             NaN         NaN  5150487            -28      C
1882350      NaN    NaN     NaN        NaN      NaN           NaN                   NaN                            NaN                   NaN                NaN  ...           NaN          NaN        NaN   NaN   NaN             NaN         NaN  5150487            -29      C

[1882350 rows x 21 columns]

In [149]:
result = df[df['Annual_Income'].apply(lambda x: isinstance(x, int))]
result

Empty DataFrame
Columns: [ID, Gender, Own_Car, Own_Realty, Children, Annual_Income, Income_Type, Education_Level, Marital_Status, Housing, Days_Birth, Days_Employed, Mobile_Phone, Work_Phone, Phone, Email, Ocupation, Family_Size]
Index: []

In [150]:
df['Annual_Income']=pd.to_numeric(df['Annual_Income'], errors='coerce')

In [151]:
result = df[df['Annual_Income'].apply(lambda x: isinstance(x, str))]
result

Empty DataFrame
Columns: [ID, Gender, Own_Car, Own_Realty, Children, Annual_Income, Income_Type, Education_Level, Marital_Status, Housing, Days_Birth, Days_Employed, Mobile_Phone, Work_Phone, Phone, Email, Ocupation, Family_Size]
Index: []

In [152]:
annual_income = df['Annual_Income'].apply(lambda x: x / 12)
annual_income

Order
1         35625.0
2         35625.0
3          9375.0
4         22500.0
5         22500.0
           ...
851731    11250.0
851732     8625.0
851733     4500.0
851734     6000.0
851735    10125.0
Name: Annual_Income, Length: 851735, dtype: float64

In [155]:
keys = ['Days_Birth','Days_Employed']
new_df = df[keys]
new_df

       Days_Birth Days_Employed
Order
1          -12005         -4542
2          -12005         -4542
3          -21474         -1134
4          -19110         -3051
5          -19110         -3051
...           ...           ...
851731   -22717.0      365243.0
851732   -15939.0       -3007.0
851733    -8169.0        -372.0
851734   -21673.0      365243.0
851735   -18858.0       -1201.0

[851735 rows x 2 columns]

In [157]:
new_df = new_df.apply(pd.to_numeric,errors='coerce')

In [158]:
df_year = new_df.applymap(lambda x: x/365)
df_year

<ipython-input-158-ed1ae09174d4>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_year = new_df.applymap(lambda x: x/365)

        Days_Birth  Days_Employed
Order
1       -32.890411     -12.443836
2       -32.890411     -12.443836
3       -58.832877      -3.106849
4       -52.356164      -8.358904
5       -52.356164      -8.358904
...            ...            ...
851731  -62.238356    1000.665753
851732  -43.668493      -8.238356
851733  -22.380822      -1.019178
851734  -59.378082    1000.665753
851735  -51.665753      -3.290411

[851735 rows x 2 columns]

In [160]:
df['Days_Employed']=pd.to_numeric(df['Days_Employed'], errors='coerce')
unemployed = df.query('Days_Employed < 0')
unemployed

             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level        Marital_Status            Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation  Family_Size
Order
1       5008804      M       Y          Y        0       427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005        -4542.0            1          1     0   0.0             NaN          2.0
2       5008805      M       Y          Y        0       427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005        -4542.0            1          1     0   0.0             NaN          2.0
3       5008806      M       Y          Y        0       112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474        -1134.0            1          0     0   0.0  Security staff          2.0
4       5008808      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
5       5008809      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...                   ...                ...        ...            ...          ...        ...   ...   ...             ...          ...
851726  6839917      F       N          Y        0       180000.0             Pensioner               Higher education               Married  House / apartment   -10966.0        -2704.0          1.0        0.0   0.0   0.0             NaN          2.0
851727  6839936      M       Y          Y        1       135000.0               Working  Secondary / secondary special               Married  House / apartment   -12569.0        -2095.0          1.0        0.0   0.0   0.0        Laborers          3.0
851732  6840222      F       N          N        0       103500.0               Working  Secondary / secondary special  Single / not married  House / apartment   -15939.0        -3007.0          1.0        0.0   0.0   0.0        Laborers          1.0
851733  6841878      F       N          N        0        54000.0  Commercial associate               Higher education  Single / not married       With parents    -8169.0         -372.0          1.0        1.0   0.0   0.0     Sales staff          1.0
851735  6842885      F       N          Y        0       121500.0               Working  Secondary / secondary special               Married  House / apartment   -18858.0        -1201.0          1.0        0.0   1.0   0.0     Sales staff          2.0

[705618 rows x 18 columns]

In [161]:
with_parents = df.query('Housing == "With parents"')
with_parents

             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level        Marital_Status       Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email              Ocupation  Family_Size
Order
255     5009078      M       N          Y        1       180000.0               Working  Secondary / secondary special               Married  With parents     -14122        -1286.0            1          0     0   0.0                Drivers          3.0
277     5009103      M       Y          Y        2       157500.0               Working  Secondary / secondary special               Married  With parents     -12859        -4056.0            1          0     1   0.0                Drivers          4.0
278     5009104      M       Y          Y        2       157500.0               Working  Secondary / secondary special               Married  With parents     -12859        -4056.0            1          0     1   0.0                Drivers          4.0
279     5009105      M       Y          Y        2       157500.0               Working  Secondary / secondary special               Married  With parents     -12859        -4056.0            1          0     1   0.0                Drivers          4.0
280     5009106      M       Y          Y        2       157500.0               Working  Secondary / secondary special               Married  With parents     -12859        -4056.0            1          0     1   0.0                Drivers          4.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...                   ...           ...        ...            ...          ...        ...   ...   ...                    ...          ...
851555  6764020      F       N          Y        0       144000.0               Working  Secondary / secondary special  Single / not married  With parents   -10574.0         -377.0          1.0        1.0   0.0   0.0                    NaN          1.0
851589  6783672      M       Y          N        0       121500.0               Working  Secondary / secondary special  Single / not married  With parents    -9698.0         -882.0          1.0        0.0   0.0   0.0  High skill tech staff          1.0
851590  6783673      M       Y          Y        0       121500.0               Working  Secondary / secondary special  Single / not married  With parents    -9698.0         -882.0          1.0        0.0   0.0   0.0  High skill tech staff          1.0
851654  6806462      F       N          N        1       157500.0               Working  Secondary / secondary special               Married  With parents   -10182.0         -886.0          1.0        0.0   1.0   0.0            Sales staff          3.0
851733  6841878      F       N          N        0        54000.0  Commercial associate               Higher education  Single / not married  With parents    -8169.0         -372.0          1.0        1.0   0.0   0.0            Sales staff          1.0

[37034 rows x 18 columns]

In [162]:
gender_keys = ['Gender', 'Annual_Income']
gender_df = df[gender_keys]
gender_df

       Gender  Annual_Income
Order
1           M       427500.0
2           M       427500.0
3           M       112500.0
4           F       270000.0
5           F       270000.0
...       ...            ...
851731      M       135000.0
851732      F       103500.0
851733      F        54000.0
851734      F        72000.0
851735      F       121500.0

[851735 rows x 2 columns]

In [173]:
for name, group in df.groupby('Marital_Status'):
  print(f"\nGroup: {name}")
  print(group)

Group: -11416
             ID Gender Own_Car Own_Realty Children  Annual_Income    Income_Type   Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone     Phone Email Ocupation  Family_Size
Order
702250  6473058      F       N          Y        1       225000.0  State servant   Sipal apartment         -11416    -247          1            0.0            0          0  Laborers   1.0       NaN          NaN
744610  6695608      M       Y          Y        1       112500.0        Working  Seipal apartment         -11416    -247          1            0.0            0          0  Laborers   1.0       NaN          NaN

Group: -14142
             ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type    Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone        Phone Email Ocupation  Family_Size
Order
507764  6112360      M       Y          N        1            NaN     Married  House / apartment         -14142   -3967          1            1.0          1.0        0.0  Secretaries   3.0       NaN          NaN

Group: -16649
            ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone       Phone Email Ocupation  Family_Size
Order
25402  5048270      F       Y          N        1       112500.0     Working     Higher ment         -16649   -5453          1            0.0            1          0  Core staff   2.0       NaN          NaN

Group: -1839
             ID Gender  Own_Car            Own_Realty                       Children  Annual_Income        Income_Type Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone   Work_Phone Phone Email Ocupation  Family_Size
Order
431569  5970347     F3  99000.0  Commercial associate  Secondary / secondary special            NaN  House / apartment          -11936          -1839       1          1            0.0            0  Sales staff   5.0   NaN       NaN          NaN

Group: -22650
             ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type    Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
330229  5796507      F       N          Y        0            NaN     Married  House / apartment         -22650  365243          1            0.0            0        0.0   NaN   2.0       NaN          NaN

Group: -22774
             ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type       Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone       Phone Email Ocupation  Family_Size
Order
456999  6060311      F       Y          N        1       202500.0     Working  Higher educatiotment         -22774    -384          1            0.0            0          0  Core staff   2.0       NaN          NaN

Group: -3967
             ID Gender Own_Car Own_Realty Children  Annual_Income        Income_Type Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone   Work_Phone Phone Email Ocupation  Family_Size
Order
465439  6605551      F       N          N        n            NaN  House / apartment          -14142          -3967       1          1            1.0            0  Secretaries   3.0   NaN       NaN          NaN

Group: -9022
             ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type    Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone     Phone Email Ocupation  Family_Size
Order
287979  5796507      F       N          Y        0            NaN     Married  House / apartment          -9022   -1283        1.0            0.0          0.0        0.0  Laborers   2.0       NaN          NaN

Group: 0
                                  ID   Gender            Own_Car Own_Realty           Children  Annual_Income Income_Type   Education_Level Marital_Status         Housing   Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
84747                        5242384        d  House / apartment     -16675              -5056            1.0           1                 1              0         Drivers          2.0            NaN          NaN        NaN   NaN   NaN       NaN          NaN
254109  5condary / secondary special  Married  House / apartment     -11866              -4384            1.0           0                 1              0             NaN          2.0            NaN          NaN        NaN   NaN   NaN       NaN          NaN
296431                       55000.0  Working  Incomplete higher      Widow  House / apartment       -19927.0       -3615                 1              0               0          1.0            NaN          1.0        NaN   NaN   NaN       NaN          NaN
499314                       6060311        F                  Y          N                  1       202500.0     Working  Higher educatio0              0               0  Sales staff            2.0          NaN        NaN   NaN   NaN       NaN          NaN
643001                       6424644        M                  N          Y                  0       315000.0   Commerc27                 1              0               1            0            NaN          2.0        NaN   NaN   NaN       NaN          NaN
795468  7condary / secondary special  Married  House / apartment     -10047               -267            1.0           1                 0              0     Sales staff          3.0            NaN          NaN        NaN   NaN   NaN       NaN          NaN
827864                     y special  Married  House / apartment     -18286              -2789            1.0           0                 0              0  Security staff          2.0            NaN          NaN        NaN   NaN   NaN       NaN          NaN

Group: 1
             ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type Education_Level Marital_Status Housing   Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
550010  6112360      M       Y          N        1            NaN      -19266          365243              1       0            0            0.0          NaN        2.0   NaN   NaN       NaN          NaN
600689  6212902      M       Y          N        2          227.0           1               0              1       0  Sales staff            2.0          NaN        NaN   NaN   NaN       NaN          NaN

Group: 1.0
             ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
203343  5581536      F       Y          Y        0        67500.0     Working         Seorers            1.0     NaN        NaN            NaN          NaN        NaN   NaN   NaN       NaN          NaN
389303  5970347   F180    -371          1        0            0.0           0        Laborers            1.0     NaN        NaN            NaN          NaN        NaN   NaN   NaN       NaN          NaN

Group: 2.0
               ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type               Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
279532    5683984      F       Y          Y        0       135000.0     Working            Secondary / seconf            2.0     NaN        NaN            NaN          NaN        NaN   NaN   NaN       NaN          NaN
321782  5872751.0      M       Y          Y        0       157500.0   Pensioner  Secondary / secondary specif            2.0     NaN        NaN            NaN          NaN        NaN   NaN   NaN       NaN          NaN
820899    6797009      F       N          Y        0       202500.0     Working        Secondary / secondarrs            2.0     NaN        NaN            NaN          NaN        NaN   NaN   NaN       NaN          NaN

Group: 3.0
             ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
423102  6605551      F       N          N        0            0.0           0             NaN            3.0     NaN        NaN            NaN          NaN        NaN   NaN   NaN       NaN          NaN

Group: 365243
             ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type              Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
228728  5536918      M       Y          N        0       450000.0   Pensioner                    Highe3153         365243       1        0.0            1.0          0.0        NaN   2.0   NaN       NaN          NaN
355508  5918187      M       N          N        1        90000.0     Working  Secondary / secondary-22115         365243       1          0            0.0            0        NaN   2.0   NaN       NaN          NaN

Group: Civil marriage
             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level  Marital_Status            Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email    Ocupation  Family_Size
Order
1       5008804      M       Y          Y        0       427500.0               Working               Higher education  Civil marriage   Rented apartment     -12005        -4542.0            1          1     0   0.0          NaN          2.0
2       5008805      M       Y          Y        0       427500.0               Working               Higher education  Civil marriage   Rented apartment     -12005        -4542.0            1          1     0   0.0          NaN          2.0
63      5008868      F       N          Y        1       211500.0         State servant  Secondary / secondary special  Civil marriage  House / apartment     -16212        -7099.0            1          0     0   0.0   Core staff          3.0
64      5008870      F       N          Y        1       211500.0         State servant  Secondary / secondary special  Civil marriage  House / apartment     -16212        -7099.0            1          0     0   0.0   Core staff          3.0
217     5009033      F       N          N        0       255150.0             Pensioner              Incomplete higher  Civil marriage   Rented apartment     -18682       365243.0            1          0     0   0.0          NaN          2.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...             ...                ...        ...            ...          ...        ...   ...   ...          ...          ...
851636  6799400      M       N          Y        0       292500.0               Working  Secondary / secondary special  Civil marriage  House / apartment   -13909.0        -6583.0          1.0        0.0   0.0   0.0     Laborers          2.0
851640  6800963      F       N          Y        0       360000.0  Commercial associate               Higher education  Civil marriage  House / apartment   -14785.0         -917.0          1.0        1.0   0.0   0.0  Sales staff          2.0
851681  6830325      F       Y          N        0       186750.0               Working  Secondary / secondary special  Civil marriage  House / apartment   -12653.0        -2457.0          1.0        0.0   0.0   0.0     Laborers          2.0
851686  6832244      F       N          Y        2       144000.0               Working  Secondary / secondary special  Civil marriage  House / apartment   -13342.0        -2999.0          1.0        0.0   0.0   0.0     Laborers          4.0
851720  6837707      M       N          Y        0       202500.0               Working               Higher education  Civil marriage  House / apartment   -13510.0        -2309.0          1.0        1.0   0.0   0.0     Laborers          2.0

[70891 rows x 18 columns]

Group: Drivers
      ID             Gender Own_Car Own_Realty Children  Annual_Income Income_Type Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
42355  d  House / apartment  -16675      -5056        1            1.0           1               0        Drivers     2.0        NaN            NaN          NaN        NaN   NaN   NaN       NaN          NaN

Group: House / apartment
             ID Gender Own_Car Own_Realty Children  Annual_Income                    Income_Type Education_Level     Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone        Email Ocupation  Family_Size
Order
524681  6137409      F       N          Y        2          135.0  Secondary / secondary special         Married  House / apartment  -20853      -1669            1.0            0        0.0   0.0     Laborers       2.0          NaN
685312  6424644      M       N          Y        0       315000.0               Commercy special         Married  House / apartment  -15709       -242            1.0            0          0     0  Accountants       3.0          NaN

Group: Married
             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level Marital_Status            Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation  Family_Size
Order
3       5008806      M       Y          Y        0       112500.0               Working  Secondary / secondary special        Married  House / apartment     -21474        -1134.0            1          0     0   0.0  Security staff          2.0
11      5008815      M       Y          Y        0       270000.0               Working               Higher education        Married  House / apartment     -16872         -769.0            1          1     1   1.0     Accountants          2.0
12      5112956      M       Y          Y        0       270000.0               Working               Higher education        Married  House / apartment     -16872         -769.0            1          1     1   1.0     Accountants          2.0
13      6153651      M       Y          Y        0       270000.0               Working               Higher education        Married  House / apartment     -16872         -769.0            1          1     1   1.0     Accountants          2.0
14      5008819      M       Y          Y        0       135000.0  Commercial associate  Secondary / secondary special        Married  House / apartment     -17778        -1194.0            1          0     0   0.0        Laborers          2.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...            ...                ...        ...            ...          ...        ...   ...   ...             ...          ...
851723  6838056      F       N          Y        0       135000.0         State servant  Secondary / secondary special        Married  House / apartment   -18997.0         -483.0          1.0        0.0   0.0   0.0             NaN          2.0
851726  6839917      F       N          Y        0       180000.0             Pensioner               Higher education        Married  House / apartment   -10966.0        -2704.0          1.0        0.0   0.0   0.0             NaN          2.0
851727  6839936      M       Y          Y        1       135000.0               Working  Secondary / secondary special        Married  House / apartment   -12569.0        -2095.0          1.0        0.0   0.0   0.0        Laborers          3.0
851734  6842765      F       N          Y        0        72000.0             Pensioner  Secondary / secondary special        Married  House / apartment   -21673.0       365243.0          1.0        0.0   0.0   0.0             NaN          2.0
851735  6842885      F       N          Y        0       121500.0               Working  Secondary / secondary special        Married  House / apartment   -18858.0        -1201.0          1.0        0.0   1.0   0.0     Sales staff          2.0

[582382 rows x 18 columns]

Group: Marrietaff
            ID Gender Own_Car Own_Realty Children  Annual_Income Income_Type                Education_Level Marital_Status Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email Ocupation  Family_Size
Order
67798  5117716      M       Y          N        0       315000.0     Working  Secondary / secondary special     Marrietaff     1.0        NaN            NaN          NaN        NaN   NaN   NaN       NaN          NaN

Group: Separated
             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level Marital_Status            Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation  Family_Size
Order
8       5008812      F       N          Y        0       283500.0             Pensioner               Higher education      Separated  House / apartment     -22464       365243.0            1          0     0   0.0             NaN          1.0
9       5008813      F       N          Y        0       283500.0             Pensioner               Higher education      Separated  House / apartment     -22464       365243.0            1          0     0   0.0             NaN          1.0
10      5008814      F       N          Y        0       283500.0             Pensioner               Higher education      Separated  House / apartment     -22464       365243.0            1          0     0   0.0             NaN          1.0
78      5008888      F       N          Y        0       247500.0  Commercial associate               Higher education      Separated   Rented apartment     -17016        -1347.0            1          0     0   0.0      Core staff          1.0
79      5008889      F       N          Y        0       247500.0  Commercial associate               Higher education      Separated   Rented apartment     -17016        -1347.0            1          0     0   0.0      Core staff          1.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...            ...                ...        ...            ...          ...        ...   ...   ...             ...          ...
851717  6837452      M       N          N        1       135000.0               Working  Secondary / secondary special      Separated  House / apartment   -12972.0         -179.0          1.0        0.0   0.0   0.0  Security staff          2.0
851728  6840098      F       N          Y        0       135000.0             Pensioner  Secondary / secondary special      Separated  House / apartment   -22717.0       365243.0          1.0        0.0   0.0   0.0             NaN          1.0
851729  6840100      F       N          Y        0       135000.0             Pensioner  Secondary / secondary special      Separated  House / apartment   -22717.0       365243.0          1.0        0.0   0.0   0.0             NaN          1.0
851730  6840102      F       N          Y        0       135000.0             Pensioner  Secondary / secondary special      Separated  House / apartment   -22717.0       365243.0          1.0        0.0   0.0   0.0             NaN          1.0
851731  6840104      M       N          Y        0       135000.0             Pensioner  Secondary / secondary special      Separated  House / apartment   -22717.0       365243.0          1.0        0.0   0.0   0.0             NaN          1.0

[52903 rows x 18 columns]

Group: Single / not married
             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level        Marital_Status            Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email    Ocupation  Family_Size
Order

In [163]:
grouped_gender = gender_df.groupby('Gender').agg({
    'Annual_Income': 'mean'
})
grouped_gender

                   Annual_Income
Gender
-2497                   0.000000
F                  174536.745496
F180                    0.000000
F3                           NaN
House / apartment       1.000000
M                  214022.770687
Married                 1.000000
Working            -19927.000000
d                       1.000000

In [165]:
key2 = ['Annual_Income', 'Days_Birth']
income_age = df[key2]
income_age

        Annual_Income Days_Birth
Order
1            427500.0     -12005
2            427500.0     -12005
3            112500.0     -21474
4            270000.0     -19110
5            270000.0     -19110
...               ...        ...
851731       135000.0   -22717.0
851732       103500.0   -15939.0
851733        54000.0    -8169.0
851734        72000.0   -21673.0
851735       121500.0   -18858.0

[851735 rows x 2 columns]

In [172]:
income_age = income_age.apply(pd.to_numeric,errors='coerce')
agg_result = income_age.agg(['mean', 'max', 'min']).astype(int)
agg_result

      Annual_Income  Days_Birth
mean         187519      -15991
max        13570000         180
min          -19927      -25201

In [174]:
df_dropna = df.dropna()
df_dropna

             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level        Marital_Status            Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation  Family_Size
Order
3       5008806      M       Y          Y        0       112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474        -1134.0            1          0     0   0.0  Security staff          2.0
4       5008808      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
5       5008809      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
6       5008810      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
7       5008811      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...                   ...                ...        ...            ...          ...        ...   ...   ...             ...          ...
851720  6837707      M       N          Y        0       202500.0               Working               Higher education        Civil marriage  House / apartment   -13510.0        -2309.0          1.0        1.0   0.0   0.0        Laborers          2.0
851727  6839936      M       Y          Y        1       135000.0               Working  Secondary / secondary special               Married  House / apartment   -12569.0        -2095.0          1.0        0.0   0.0   0.0        Laborers          3.0
851732  6840222      F       N          N        0       103500.0               Working  Secondary / secondary special  Single / not married  House / apartment   -15939.0        -3007.0          1.0        0.0   0.0   0.0        Laborers          1.0
851733  6841878      F       N          N        0        54000.0  Commercial associate               Higher education  Single / not married       With parents    -8169.0         -372.0          1.0        1.0   0.0   0.0     Sales staff          1.0
851735  6842885      F       N          Y        0       121500.0               Working  Secondary / secondary special               Married  House / apartment   -18858.0        -1201.0          1.0        0.0   1.0   0.0     Sales staff          2.0

[591235 rows x 18 columns]

In [175]:
df_fillna = df.fillna(9999999999)
df_fillna

             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level        Marital_Status            Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation  Family_Size
Order
1       5008804      M       Y          Y        0       427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005        -4542.0            1          1     0   0.0      9999999999          2.0
2       5008805      M       Y          Y        0       427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005        -4542.0            1          1     0   0.0      9999999999          2.0
3       5008806      M       Y          Y        0       112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474        -1134.0            1          0     0   0.0  Security staff          2.0
4       5008808      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
5       5008809      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...                   ...                ...        ...            ...          ...        ...   ...   ...             ...          ...
851731  6840104      M       N          Y        0       135000.0             Pensioner  Secondary / secondary special             Separated  House / apartment   -22717.0       365243.0          1.0        0.0   0.0   0.0      9999999999          1.0
851732  6840222      F       N          N        0       103500.0               Working  Secondary / secondary special  Single / not married  House / apartment   -15939.0        -3007.0          1.0        0.0   0.0   0.0        Laborers          1.0
851733  6841878      F       N          N        0        54000.0  Commercial associate               Higher education  Single / not married       With parents    -8169.0         -372.0          1.0        1.0   0.0   0.0     Sales staff          1.0
851734  6842765      F       N          Y        0        72000.0             Pensioner  Secondary / secondary special               Married  House / apartment   -21673.0       365243.0          1.0        0.0   0.0   0.0      9999999999          2.0
851735  6842885      F       N          Y        0       121500.0               Working  Secondary / secondary special               Married  House / apartment   -18858.0        -1201.0          1.0        0.0   1.0   0.0     Sales staff          2.0

[851735 rows x 18 columns]

In [177]:
imputer = SimpleImputer(strategy='mean')

In [181]:
DF = df
impute_columns = ['Annual_Income', 'Days_Birth', 'Days_Employed', 'Family_Size']
DF = DF.apply(pd.to_numeric,errors='coerce')
result = DF[DF['Days_Birth'].apply(lambda x: isinstance(x, str))]
result

Empty DataFrame
Columns: [ID, Gender, Own_Car, Own_Realty, Children, Annual_Income, Income_Type, Education_Level, Marital_Status, Housing, Days_Birth, Days_Employed, Mobile_Phone, Work_Phone, Phone, Email, Ocupation, Family_Size]
Index: []

In [182]:
DF[impute_columns] = imputer.fit_transform(DF[impute_columns])
df

             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level        Marital_Status            Housing Days_Birth  Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation  Family_Size
Order
1       5008804      M       Y          Y        0       427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005        -4542.0            1          1     0   0.0             NaN          2.0
2       5008805      M       Y          Y        0       427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005        -4542.0            1          1     0   0.0             NaN          2.0
3       5008806      M       Y          Y        0       112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474        -1134.0            1          0     0   0.0  Security staff          2.0
4       5008808      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
5       5008809      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110        -3051.0            1          0     1   1.0     Sales staff          1.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...                   ...                ...        ...            ...          ...        ...   ...   ...             ...          ...
851731  6840104      M       N          Y        0       135000.0             Pensioner  Secondary / secondary special             Separated  House / apartment   -22717.0       365243.0          1.0        0.0   0.0   0.0             NaN          1.0
851732  6840222      F       N          N        0       103500.0               Working  Secondary / secondary special  Single / not married  House / apartment   -15939.0        -3007.0          1.0        0.0   0.0   0.0        Laborers          1.0
851733  6841878      F       N          N        0        54000.0  Commercial associate               Higher education  Single / not married       With parents    -8169.0         -372.0          1.0        1.0   0.0   0.0     Sales staff          1.0
851734  6842765      F       N          Y        0        72000.0             Pensioner  Secondary / secondary special               Married  House / apartment   -21673.0       365243.0          1.0        0.0   0.0   0.0             NaN          2.0
851735  6842885      F       N          Y        0       121500.0               Working  Secondary / secondary special               Married  House / apartment   -18858.0        -1201.0          1.0        0.0   1.0   0.0     Sales staff          2.0

[851735 rows x 18 columns]

In [183]:
df.isnull().sum()

ID                  0
Gender              0
Own_Car             0
Own_Realty          0
Children            0
                ...
Work_Phone         24
Phone              24
Email              28
Ocupation      260497
Family_Size        38
Length: 18, dtype: int64

In [185]:
selected_columns = ['Annual_Income', 'Days_Birth', 'Days_Employed', 'Family_Size']
DF[selected_columns].isnull().sum()

Annual_Income    0
Days_Birth       0
Days_Employed    0
Family_Size      0
dtype: int64

In [153]:
df

             ID Gender Own_Car Own_Realty Children  Annual_Income           Income_Type                Education_Level        Marital_Status            Housing Days_Birth Days_Employed Mobile_Phone Work_Phone Phone Email       Ocupation  Family_Size
Order
1       5008804      M       Y          Y        0       427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542            1          1     0   0.0             NaN          2.0
2       5008805      M       Y          Y        0       427500.0               Working               Higher education        Civil marriage   Rented apartment     -12005         -4542            1          1     0   0.0             NaN          2.0
3       5008806      M       Y          Y        0       112500.0               Working  Secondary / secondary special               Married  House / apartment     -21474         -1134            1          0     0   0.0  Security staff          2.0
4       5008808      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051            1          0     1   1.0     Sales staff          1.0
5       5008809      F       N          Y        0       270000.0  Commercial associate  Secondary / secondary special  Single / not married  House / apartment     -19110         -3051            1          0     1   1.0     Sales staff          1.0
...         ...    ...     ...        ...      ...            ...                   ...                            ...                   ...                ...        ...           ...          ...        ...   ...   ...             ...          ...
851731  6840104      M       N          Y        0       135000.0             Pensioner  Secondary / secondary special             Separated  House / apartment   -22717.0      365243.0          1.0        0.0   0.0   0.0             NaN          1.0
851732  6840222      F       N          N        0       103500.0               Working  Secondary / secondary special  Single / not married  House / apartment   -15939.0       -3007.0          1.0        0.0   0.0   0.0        Laborers          1.0
851733  6841878      F       N          N        0        54000.0  Commercial associate               Higher education  Single / not married       With parents    -8169.0        -372.0          1.0        1.0   0.0   0.0     Sales staff          1.0
851734  6842765      F       N          Y        0        72000.0             Pensioner  Secondary / secondary special               Married  House / apartment   -21673.0      365243.0          1.0        0.0   0.0   0.0             NaN          2.0
851735  6842885      F       N          Y        0       121500.0               Working  Secondary / secondary special               Married  House / apartment   -18858.0       -1201.0          1.0        0.0   1.0   0.0     Sales staff          2.0

[851735 rows x 18 columns]

## Your task

* Inspect a dataframe with `df.head()`, `df.tail()`, `df.info()`, `df.describe()`.
* Show how many missing values in your data, each column.
* Manipulate how a dataframe displays in Jupyter by modifying Pandas configuration options such as `pd.set_option("display.max_rows", n)`.
* Rename columns of a dataframe using the `df.rename()` function or by accessing the `df.columns` attribute.
* Modify the index name and index values of a dataframe using `.set_index()`, `.reset_index()` , `df.index.name`, `.index`.
* Use `df.melt()` and `df.pivot()` to reshape dataframes, specifically to make tidy dataframes.
* Combine dataframes using `df.merge()` and `pd.concat()` and know when to use these different methods.
* Apply functions to a dataframe `df.apply()` and `df.applymap()`
* Find the data which satisfy specific condition using `df.query()`
* Perform grouping and aggregating operations using `df.groupby()` and `df.agg()`.
* Perform aggregating methods on grouped or ungrouped objects such as finding the minimum, maximum and sum of values in a dataframe using `df.agg()`.
* Remove or fill missing values in a dataframe with `df.dropna()` and `df.fillna()` please practice using different method of filling missing value.
* Practice imputing missing values using the `SimpleImputer` Class in `sklearn`

## For extra miles:


1.   clean your text data using regex function
2.   clean the text and nested json in https://raw.githubusercontent.com/nnqomariyah/Fundamentals_of_Data_Science/main/week_3/data/movies_metadata.csv